services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    network_mode: "host" ## Temp fix
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "4000:3000"
    env_file:
      - .env
    restart: always
    network_mode: "host" ## Temp fix
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bikedb
      MONGO_REPLICA_PORT: 27017
    restart: always
    network_mode: "host" ## Temp fix